// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ProCodeGuide_MLNET_SampleML.Model
{
    public class ModelInput
    {
        [ColumnName("col0"), LoadColumn(0)]
        public string Col0 { get; set; }


        [ColumnName("col1"), LoadColumn(1)]
        public string Col1 { get; set; }


    }
}
